[Configuration]
BasedOn=..\Engine\Config\BaseEditor.ini


[ModPackages]
ModPackagesInPath=..\..\SanctumGame\Src
ModOutputDir=..\..\SanctumGame\Unpublished\CookedPC\Script

; Prevent som crashes...
[Cooker.GeneralOptions]
bDisablePMapObjectChecking=TRUE