[Configuration]
BasedOn=..\Engine\Config\BaseInput.ini

[Engine.PlayerInput]

;-Bindings=(Name="MoveForward",Command="Axis aBaseY Speed=1.0")
;-Bindings=(Name="W",Command="MoveForward")

;-Bindings=(Name="MoveBackward",Command="Axis aBaseY Speed=-1.0")
;-Bindings=(Name="S",Command="MoveBackward")


[Sanctum.SanctumPlayerInput]
.Bindings=(Name="Escape",Command="togglePause")
.Bindings=(Name="F1",Command="ToggleDebugControls")

.Bindings=(Name="MouseX",Command="Count bXAxis | Axis aMouseX")
.Bindings=(Name="MouseY",Command="Count bYAxis | Axis aMouseY")

.Bindings=(Name="Mouse_PrevWeapon",Command="PrevWeapon")
.Bindings=(Name="Mouse_NextWeapon",Command="NextWeapon")


.Bindings=(Name="GBA_Forward",Command="Axis aBaseY Speed=1.0")
.Bindings=(Name="GBA_Back",Command="Axis aBaseY Speed=-1.0")
.Bindings=(Name="GBA_StrafeLeft",Command="Axis aStrafe Speed=-1.0")
.Bindings=(Name="GBA_StrafeRight",Command="Axis aStrafe Speed=+1.0")
.Bindings=(Name="GBA_Jump",Command="Jump | Axis aUp Speed=+1.0 AbsoluteAxis=100")
.Bindings=(Name="GBA_Fire",Command="BeginFire | OnRelease StopFire")
.Bindings=(Name="GBA_AltFire",Command="StartAltFire | OnRelease StopAltFire")
.Bindings=(Name="GBA_Use",Command="use")
.Bindings=(Name="GBA_PrevWeapon",Command="PrevWeapon")
.Bindings=(Name="GBA_NextWeapon",Command="NextWeapon")
.Bindings=(Name="GBA_SwitchWeapon1",Command="switchweapon 1")
.Bindings=(Name="GBA_SwitchWeapon2",Command="switchweapon 2")
.Bindings=(Name="GBA_SwitchWeapon3",Command="switchweapon 3")
.Bindings=(Name="GBA_storeSwitch",Command="storeSwitch")
.Bindings=(Name="GBA_Talk",Command="talk")
.Bindings=(Name="GBA_ToggleOverview",Command="ToggleOverview")


.Bindings=(Name="W",Command="GBA_Forward")
.Bindings=(Name="S",Command="GBA_Back")
.Bindings=(Name="A",Command="GBA_StrafeLeft")
.Bindings=(Name="D",Command="GBA_StrafeRight")
.Bindings=(Name="SpaceBar",Command="GBA_Jump")
.Bindings=(Name="T",Command="GBA_Talk")
.Bindings=(Name="F",Command="GBA_PrevElevator")
.Bindings=(Name="G",Command="GBA_NextElevator")

.Bindings=(Name="LeftMouseButton",Command="GBA_Fire")
.Bindings=(Name="RightMouseButton",Command="GBA_AltFire")
.Bindings=(Name="MouseScrollUp",Command="Mouse_PrevWeapon")
.Bindings=(Name="MouseScrollDown",Command="Mouse_NextWeapon")
.Bindings=(Name="one",Command="GBA_SwitchWeapon1")
.Bindings=(Name="two",Command="GBA_SwitchWeapon2")
.Bindings=(Name="three",Command="GBA_SwitchWeapon3")
.Bindings=(Name="LeftShift",Command="GBA_storeSwitch")



.Bindings=(Name="TAB",Command="GBA_ToggleOverview")
.Bindings=(Name="E",Command="GBA_NextWeapon")
.Bindings=(Name="Q",Command="GBA_PrevWeapon")
.Bindings=(Name="Enter",Command="GBA_Use" )
.Bindings=(Name="SpaceBar",Command="GBA_Jump")

.Bindings=(Name="GBA_PingCommand",Command="Button mPingButton")
.Bindings=(Name="LeftAlt",Command="GBA_PingCommand")
;.Bindings=(Name="GBA_PingCommand",Command="BeginFire")


.Bindings=(Name="GBA_Jump_Gamepad",Command="SmartJump | Axis aUp Speed=1.0 AbsoluteAxis=100")
.Bindings=(Name="GBA_StrafeLeft_Gamepad",Command="Axis aStrafe Speed=1.0 DeadZone=0.2")
.Bindings=(Name="GBA_MoveForward_Gamepad",Command="Axis aBaseY Speed=1.0 DeadZone=0.2")
.Bindings=(Name="GBA_TurnLeft_Gamepad",Command="Axis aTurn Speed=1.0 DeadZone=0.2")
.Bindings=(Name="GBA_Look_Gamepad",Command="Axis aLookup Speed=0.65 DeadZone=0.2")
.Bindings=(Name="GBA_storeSwitch_Gamepad",Command="storeSwitch")
.Bindings=(Name="GBA_Fire_Gamepad",Command="BeginFire_Gamepad true | OnRelease StopFire"  )


;-----------------------------------------------------------------------------------------
; Game Controller Bindings
;-----------------------------------------------------------------------------------------

; Secondary default bindings
.Bindings=(Name="XboxTypeS_LeftThumbstick",Command="GBA_Jump_Gamepad")

; Primaray default bindings
.Bindings=(Name="XboxTypeS_Start",Command="togglePause")
.Bindings=(Name="XboxTypeS_LeftX",Command="GBA_StrafeLeft_Gamepad")
.Bindings=(Name="XboxTypeS_LeftY",Command="GBA_MoveForward_Gamepad")
.Bindings=(Name="XboxTypeS_RightX",Command="GBA_TurnLeft_Gamepad")
.Bindings=(Name="XboxTypeS_RightY",Command="GBA_Look_Gamepad")
.Bindings=(Name="XboxTypeS_RightShoulder",Command="GBA_NextWeapon")
.Bindings=(Name="XboxTypeS_RightTrigger",Command="GBA_Fire_Gamepad")
.Bindings=(Name="XboxTypeS_LeftShoulder",Command="GBA_PrevWeapon")
.Bindings=(Name="XboxTypeS_LeftTrigger",Command="GBA_AltFire")
.Bindings=(Name="XboxTypeS_A",Command="GBA_Jump_Gamepad")
.Bindings=(Name="XboxTypeS_X",Command="GBA_storeSwitch_Gamepad")
.Bindings=(Name="XboxTypeS_Y",Command="GBA_ToggleOverview")
.Bindings=(Name="XboxTypeS_Back",Command="GBA_Use")
.Bindings=(Name="XboxTypeS_DPad_Up",Command="switchweapon 2")
.Bindings=(Name="XboxTypeS_DPad_Left",Command="switchweapon 1")
.Bindings=(Name="XboxTypeS_DPad_Right",Command="switchweapon 3")
