[Configuration]
BasedOn=..\Engine\Config\BaseEngine.ini

[URL]
MapExt=sanctum
Map=Sanctum2_CharacterSelection.sanctum
LocalMap=LegalLevel.sanctum
;LocalOptions=open LegalLevel.sanctum
TransitionMap=TransitionMap.sanctum
EXEName=SanctumGame.exe
DebugEXEName=DEBUG-SanctumGame.exe
GameName=Sanctum Game
GameNameShort=SG

[Engine.ScriptPackages]
+NativePackages=UDKBase
+NativePackages=SanctumGame
+ContainsDynamicResource=SanctumGameDLC1
+ContainsDynamicResource=SanctumGameDLC2
+ContainsDynamicResource=SanctumGameDLC3
+ContainsDynamicResource=SanctumGameDLC4

[Core.System]
+Paths=..\..\SanctumGame\Content
+Paths=..\..\SanctumGame\__Trashcan
+LocalizationPaths=..\..\SanctumGame\Localization
SavePath=..\..\SanctumGame\Save
+Extensions=udk
+Extensions=sanctum
SeekFreePCPaths=..\..\SanctumGame\CookedPC
SeekFreePCExtensions=xxx
MaxObjectsNotConsideredByGC=75149
SizeOfPermanentObjectPool=9849576

[Engine.Engine]
bEnableColorClear=TRUE
;NetworkDevice=OnlineSubsystemSteamworks.IpNetDriverSteamworks
ScoutClassName=SanctumGame.SGScout
;ConsoleClassName=SanctumGame.SanctumConsole
GameViewportClientClassName=SanctumGame.SGGameViewportClient
;TinyFontName=sanctumfonts.NormalFont
;SmallFontName=sanctumfonts.NormalFont
;MediumFontName=sanctumfonts.NormalFont
;LargeFontName=sanctumfonts.NormalFont
;SubtitleFontName=sanctumfonts.NormalFont
DefaultPostProcessName=Sanctum_AlwaysLoaded.PostProcessChains.PostProcessChain
GameEngine=SanctumGame.SGEngine
Language=XXX
bUseRecastNavMesh=true
LocalPlayerClassName=SanctumGame.SGLocalPlayer
AdditionalFontNames[0]=Sanctumfonts.Xbox360_18pt
AdditionalFontNames[1]=Sanctumfonts.PC_Font
AdditionalFontNames[2]=Sanctumfonts.NormalFont

+ActiveClassRedirects=(OldClassName="SGEnemyWalkerPup",NewClassName="SanctumGame.SGEnemyWalkerPup")
+ActiveClassRedirects=(OldClassName="SGEnemyWalkerWarrior",NewClassName="SanctumGame.SGEnemyWalkerWarrior")
+ActiveClassRedirects=(OldClassName="SGEnemyWalkerPatriarch",NewClassName="SanctumGame.SGEnemyWalkerPatriarch")
+ActiveClassRedirects=(OldClassName="SGEnemyFlyerShooter",NewClassName="SanctumGame.SGEnemyFlyerShooter")
+ActiveClassRedirects=(OldClassName="SGEnemyHeavy",NewClassName="SanctumGame.SGEnemyHeavy")
+ActiveClassRedirects=(OldClassName="SGEnemyHoverer",NewClassName="SanctumGame.SGEnemyHoverer")
+ActiveClassRedirects=(OldClassName="SGEnemyHovererQueen",NewClassName="SanctumGame.SGEnemyHovererQueen")
+ActiveClassRedirects=(OldClassName="SGEnemyRhino",NewClassName="SanctumGame.SGEnemyRhino")
+ActiveClassRedirects=(OldClassName="SGEnemyRunner",NewClassName="SanctumGame.SGEnemyRunner")
+ActiveClassRedirects=(OldClassName="SGEnemyRunnerFatty",NewClassName="SanctumGame.SGEnemyRunnerFatty")
+ActiveClassRedirects=(OldClassName="SGEnemyScreamer",NewClassName="SanctumGame.SGEnemyScreamer")
+ActiveClassRedirects=(OldClassName="SGEnemyScreamerFatty",NewClassName="SanctumGame.SGEnemyScreamerFatty")
+ActiveClassRedirects=(OldClassName="SGEnemySnorker",NewClassName="SanctumGame.SGEnemySnorker")
+ActiveClassRedirects=(OldClassName="SGEnemySoaker",NewClassName="SanctumGame.SGEnemySoaker")
+ActiveClassRedirects=(OldClassName="SGEnemySuperHeavy",NewClassName="SanctumGame.SGEnemySuperHeavy")
+ActiveClassRedirects=(OldClassName="SGEnemyWalker",NewClassName="SanctumGame.SGEnemyWalker")
+ActiveClassRedirects=(OldClassName="SGEnemyWalkerPatriarch",NewClassName="SanctumGame.SGEnemyWalkerPatriarch")
+ActiveClassRedirects=(OldClassName="SGEnemyWalkerPup",NewClassName="SanctumGame.SGEnemyWalkerPup")
+ActiveClassRedirects=(OldClassName="SGEnemyWalkerWarrior",NewClassName="SanctumGame.SGEnemyWalkerWarrior")
+ActiveClassRedirects=(OldClassName="SGEnemyBobbleHead",NewClassName="SanctumGame.SGEnemyBobbleHead")

+ActiveClassRedirects=(OldClassName="SGExplosiveBarrel",NewClassName="SanctumGameContent.SGExplosiveBarrel")
+ActiveClassRedirects=(OldClassName="SGExplosiveFlower",NewClassName="SanctumGameContent.SGExplosiveFlower")
+ActiveClassRedirects=(OldClassName="SGExplosiveBarrelFacility",NewClassName="SanctumGameContent.SGExplosiveBarrelFacility")

+ActiveClassRedirects=(OldClassName="SGMineBlomSvulst",NewClassName="SanctumGameContent.SGMineBlomSvulst")
+ActiveClassRedirects=(OldClassName="SGMinePlaceable",NewClassName="SanctumGameContent.SGMinePlaceable")
+ActiveClassRedirects=(OldClassName="SGMineBlomSvulstPlaceable",NewClassName="SanctumGameContent.SGMineBlomSvulstPlaceable")

+ActiveClassRedirects=(OldClassName="SGInfantryExplorerPlaceable",NewClassName="SanctumGameContent.SGInfantryExplorerPlaceable")

+ActiveClassRedirects=(OldClassName="SGFamilyInfoExplorer",NewClassName="SanctumGame.SGFamilyInfoExplorer")
+ActiveClassRedirects=(OldClassName="SGFamilyInfoExplorerAssault",NewClassName="SanctumGame.SGFamilyInfoExplorerAssault")

+ActiveClassRedirects=(OldClassName="SGPawnSoundGroupEnemyWalkerPup",NewClassName="SanctumGame.SGPawnSoundGroupEnemyWalkerPup")
+ActiveClassRedirects=(OldClassName="SGPawnSoundGroupEnemyWalkerWarrior",NewClassName="SanctumGame.SGPawnSoundGroupEnemyWalkerWarrior")
+ActiveClassRedirects=(OldClassName="SGPawnSoundGroupEnemyWalkerPatriarch",NewClassName="SanctumGame.SGPawnSoundGroupEnemyWalkerPatriarch")
+ActiveClassRedirects=(OldClassName="SGPawnSoundGroupEnemyWalker",NewClassName="SanctumGame.SGPawnSoundGroupEnemyWalker")
+ActiveClassRedirects=(OldClassName="SGPawnSoundGroupEnemySuperHeavy",NewClassName="SanctumGame.SGPawnSoundGroupEnemySuperHeavy")
+ActiveClassRedirects=(OldClassName="SGPawnSoundGroupEnemySoaker",NewClassName="SanctumGame.SGPawnSoundGroupEnemySoaker")
+ActiveClassRedirects=(OldClassName="SGPawnSoundGroupEnemySnorker",NewClassName="SanctumGame.SGPawnSoundGroupEnemySnorker")
+ActiveClassRedirects=(OldClassName="SGPawnSoundGroupEnemyScreamerFatty",NewClassName="SanctumGame.SGPawnSoundGroupEnemyScreamerFatty")
+ActiveClassRedirects=(OldClassName="SGPawnSoundGroupEnemyScreamer",NewClassName="SanctumGame.SGPawnSoundGroupEnemyScreamer")
+ActiveClassRedirects=(OldClassName="SGPawnSoundGroupEnemyRunnerFatty",NewClassName="SanctumGame.SGPawnSoundGroupEnemyRunnerFatty")
+ActiveClassRedirects=(OldClassName="SGPawnSoundGroupEnemyRunner",NewClassName="SanctumGame.SGPawnSoundGroupEnemyRunner")
+ActiveClassRedirects=(OldClassName="SGPawnSoundGroupEnemyRhino",NewClassName="SanctumGame.SGPawnSoundGroupEnemyRhino")
+ActiveClassRedirects=(OldClassName="SGPawnSoundGroupEnemyHovererQueen",NewClassName="SanctumGame.SGPawnSoundGroupEnemyHovererQueen")
+ActiveClassRedirects=(OldClassName="SGPawnSoundGroupEnemyHoverer",NewClassName="SanctumGame.SGPawnSoundGroupEnemyHoverer")
+ActiveClassRedirects=(OldClassName="SGPawnSoundGroupEnemyHeavy",NewClassName="SanctumGame.SGPawnSoundGroupEnemyHeavy")
+ActiveClassRedirects=(OldClassName="SGPawnSoundGroupEnemyFlyerShooter",NewClassName="SanctumGame.SGPawnSoundGroupEnemyFlyerShooter")
+ActiveClassRedirects=(OldClassName="SGPawnSoundGroupEnemyBobbleHead",NewClassName="SanctumGame.SGPawnSoundGroupEnemyBobbleHead")

+ActiveClassRedirects=(OldClassName="SGEnemyAirBoss",NewClassName="SanctumGameDLC1.SGEnemyAirBoss")
+ActiveClassRedirects=(OldClassName="SGEnemyMutator",NewClassName="SanctumGameDLC1.SGEnemyMutator")
+ActiveClassRedirects=(OldClassName="SGEnemyAirHealer",NewClassName="SanctumGameDLC1.SGEnemyAirHealer")

+ActiveClassRedirects=(OldClassName="SGEnemyFlyingFolder",NewClassName="SanctumGameDLC2.SGEnemyAirFlyingFolder")
+ActiveClassRedirects=(OldClassName="SGEnemyHeavyMini",NewClassName="SanctumGameDLC2.SGEnemyHeavyMini")
+ActiveClassRedirects=(OldClassName="SGEnemyInfectedExplorer",NewClassName="SanctumGameDLC2.SGEnemyInfectedExplorer")
+ActiveClassRedirects=(OldClassName="SGEnemyJumper",NewClassName="SanctumGameDLC2.SGEnemyJumper")

+ActiveClassRedirects=(OldClassName="SGEnemyJumpSpitterBoss",NewClassName="SanctumGameDLC3.SGEnemyJumpSpitterBoss")
+ActiveClassRedirects=(OldClassName="SGEnemySporePod",NewClassName="SanctumGameDLC3.SGEnemyAirSporePod")
+ActiveClassRedirects=(OldClassName="SGEnemyWalkerArmored",NewClassName="SanctumGameDLC3.SGEnemyWalkerArmored")

+ActiveClassRedirects=(OldClassName="SGExplosiveFlowerAcid",NewClassName="SanctumGameContentDLC1.SGExplosiveFlowerAcid")
+ActiveClassRedirects=(OldClassName="SGExplosiveFlowerFire",NewClassName="SanctumGameContentDLC1.SGExplosiveFlowerFire")
+ActiveClassRedirects=(OldClassName="SGExplosiveFlowerKlase",NewClassName="SanctumGameContentDLC1.SGExplosiveFlowerKlase")
+ActiveClassRedirects=(OldClassName="SGExplosiveFlowerStun",NewClassName="SanctumGameContentDLC1.SGExplosiveFlowerStun")

+ActiveClassRedirects=(OldClassName="SGEnemyHeavyMini",NewClassName="SanctumGameDLC3.SGEnemyHeavyMini")
+ActiveClassRedirects=(OldClassName="SGEnemyAirFlyingFolder",NewClassName="SanctumGameDLC3.SGEnemyAirFlyingFolder")
+ActiveClassRedirects=(OldClassName="SGEnemyJumpSpitterBoss",NewClassName="SanctumGameDLC4.SGEnemyJumpSpitterBoss")

[Engine.GameEngine]
DownloadableContentEnumeratorClassName="Engine.DownloadableContentEnumerator"
DownloadableContentManagerClassName="SanctumGame.SGDownloadableContentManager"


[Engine.PackagesToAlwaysCook]
+Package=Sanctum_AlwaysLoaded
+Package=UI_FrontEnd
+Package=UI_Common
+Package=UI_LocalizedFonts
+Package=UI_InGame
+Package=UI_MenuOnly

+SeekFreePackage=CH_Character_PreSelection

;DLC 1
+SeekFreePackage=CH_Tsygan_End_Anim
+SeekFreePackage=Sanctum_Overlay_DLC_01
+SeekFreePackage=SanctumGameDLC1
+SeekFreePackage=UI_LoadingDLC1
+SeekFreePackage=UI_Unlock_DLC1
+SeekFreePackage=UI_Portraits_DLC_01
+SeekFreePackage=Sanctum_Music_DLC01_Action
+SeekFreePackage=Sanctum_Music_DLC01_Boss
+SeekFreePackage=Sanctum_Music_DLC01_Build
+SeekFreePackage=CH_Character_PreSelection_DLC1


;DLC2
+SeekFreePackage=SanctumGameDLC2
+SeekFreePackage=UI_LoadingDLC2
+SeekFreePackage=Sanctum_Overlay_DLC_02
+SeekFreePackage=SG_Music_Slums_Action
+SeekFreePackage=SG_Music_Slums_Build
+SeekFreePackage=UI_Unlock_DLC2

;DLC3
+SeekFreePackage=SanctumGameDLC3
+SeekFreePackage=UI_LoadingDLC3
+SeekFreePackage=Sanctum_Overlay_DLC_03
+SeekFreePackage=UI_Unlock_DLC3

;DLC4
+SeekFreePackage=SanctumGameDLC4
+SeekFreePackage=UI_LoadingDLC4
+SeekFreePackage=Sanctum_Overlay_DLC_04
+SeekFreePackage=UI_Unlock_DLC4
+SeekFreePackage=Sanctum_Music_Misc
+SeekFreePackage=SG_Music_Arc_Build 
+SeekFreePackage=SG_Music_Arc_Action 

+SeekFreePackage=UI_LoadingBasic
+SeekFreePackage=UI_Loading
+SeekFreePackage=Sanctum_Overlay
+SeekFreePackage=UI_Portraits
+SeekFreePackage=UI_Unlock
+SeekFreePackage=UI_LobbyBackground_Original
+SeekFreePackage=UI_MapIcons

+SeekFreePackage=CH_Haigen_End_Anim
+SeekFreePackage=CH_Simo_End_Anim
+SeekFreePackage=CH_Skye_End_Anim
+SeekFreePackage=CH_Sweet_End_Anim
+SeekFreePackage=SG_Music_Boss_01
+SeekFreePackage=SG_Music_Boss_02
+SeekFreePackage=SG_Music_Boss_03
+SeekFreePackage=SG_Music_Defeat
+SeekFreePackage=SG_Music_Endboss_01
+SeekFreePackage=SG_Music_Facility_Action_01
+SeekFreePackage=SG_Music_Facility_Action_02
+SeekFreePackage=SG_Music_Facility_Build
+SeekFreePackage=SG_Music_GT_Action_01
+SeekFreePackage=SG_Music_GT_Action_02
+SeekFreePackage=SG_Music_GT_Build
+SeekFreePackage=SG_Music_Jungle_Action
+SeekFreePackage=SG_Music_Jungle_Build
+SeekFreePackage=SG_Music_MT_Ending
+SeekFreePackage=SG_Music_RF_Action
+SeekFreePackage=SG_Music_RF_Build
+SeekFreePackage=SG_Music_Swamp_Action
+SeekFreePackage=SG_Music_Swamp_Build_02
+SeekFreePackage=SG_Music_Swamp_Build_01
+SeekFreePackage=SG_Music_Swamp_End_Action
+SeekFreePackage=SG_Music_Swamp_End_Build
+SeekFreePackage=SG_Music_Win
+SeekFreePackage=SG_Music_LastWave

[Engine.PackagesToForceCookPerMap]
.Map=Sanctum2_MenuLobby
.Package=UI_LobbyBackground_Original
.Package=UI_LobbyBackground_DLC_01
.Package=UI_LobbyBackground_DLC_02
.Package=UI_LobbyBackground_DLC_03
.Package=UI_LobbyBackground_DLC_04
.Package=UI_MapIcons

[Engine.DataStoreClient]
+PlayerDataStoreClassNames=Engine.UIDataStore_OnlinePlayerData
+GlobalDataStoreClasses=SanctumGame.SGUIDataStore_OnlineGameSettings
+GlobalDataStoreClasses=SanctumGame.SGDataStore_GameSearch

[Engine.UIDataStore_OnlinePlayerData]
ProfileSettingsClassName=SanctumGame.SGProfileSettings
PlayerStorageClassName=SanctumGame.SGOnlinePlayerStorage
StorageProviderClassName=SanctumGame.SGDataProvider_Progression
FriendsProviderClassName=SanctumGame.SGDataProvider_OnlineFriends

[Engine.StartupPackages]
;+Package=SanctumFonts
+Package=UI_Common
+Package=UI_LocalizedFonts
+Package=Sanctum_AlwaysLoaded
+Package=SanctumFonts

[UnrealEd.EditorEngine]
EditPackagesOutPath=..\..\SanctumGame\Script
FRScriptOutputPath=..\..\SanctumGame\ScriptFinalRelease
+EditPackages=UDKBase
+EditPackages=SanctumGame
+EditPackages=SanctumGameContent
;DLC1
+EditPackages=SanctumGameDLC1
+EditPackages=SanctumGameContentDLC1
;DLC2
+EditPackages=SanctumGameDLC2
;+EditPackages=SanctumGameContentDLC2
;DLC3
+EditPackages=SanctumGameDLC3
;+EditPackages=SanctumGameContentDLC3
;DLC4
+EditPackages=SanctumGameDLC4
+EditPackages=SanctumGameContentDLC4
;Prototyping
+EditPackages=SanctumGamePrototyping
LocalPlayerClassName=SanctumGame.SGLocalPlayer
AutoSaveDir=..\..\SanctumGame\Autosaves
InEditorGameURLOptions=

[SystemSettingsEditor]
ResX=1280
ResY=1024

[Windows.StandardUser]
MyDocumentsSubDirName=Sanctum2

[MobileSupport]
bShouldCachePVRTCTextures=False
bShouldCacheATITCTextures=False
bShouldCacheFlashTextures=False
bShouldFlattenMaterials=False

[OnlineSubsystemGameSpy.OnlineSubsystemGameSpy]
bHasGameSpyAccount=true
EncryptedProductKey=NotForShip
ProfileDataDirectory=../SanctumGame/SaveData
ProfileDataExtension=.ue3profile
ProductID=11097
NamespaceID=40
PartnerID=33
GameID=1727
StatsVersion=7
NickStatsKeyId=1
PlaceStatsKeyId=2
+LocationUrlsForInvites="sanctumpc"
LocationUrl="sanctumpc"
bShouldUseMcp=true

[Engine.OnlineSubsystem]
NamedInterfaceDefs=(InterfaceName="RecentPlayersList",InterfaceClassName="SanctumGame.SGOnlineRecentPlayersList")

[OnlineSubsystemSteamworks.OnlineSubsystemSteamworks]
bUseVAC=true
GameDir=unrealtest
GameVersion=1.0.0.0
Region=255
CurrentNotificationPosition=8
ResetStats=0

[OnlineSubsystemSteam.OnlineSubsystemSteam]
CurrentNotificationPosition=6
bRelaunchInSteam=true
RelaunchAppId=210770

[VoIP]
VolumeThreshold=0.1
bHasVoiceEnabled=true

[Cooker.FaceFXOptions]
bGeneratePersistentMapAnimSet=TRUE

[FullScreenMovie]
LoadMapMovies=UI_Loading_Special.LoadingScreenSpecial_01
bShouldStopMovieAtEndOfLoadMap=true

[IpDrv.TcpNetDriver]
ConnectionTimeout=20.0
InitialConnectTimeout=30.0

[Engine.LocalPlayer]
mDidAlterKeyBindings=false
