[Configuration]
BasedOn=..\Engine\Config\BaseUI.ini

[SanctumGame.SGControllerTag]
+mExtraActionsArray=( Action = "Menu_Confirm", Input = "XboxTypeS_A" )
+mExtraActionsArray=( Action = "Menu_Cancel", Input = "XboxTypeS_B" )
+mExtraActionsArray=( Action = "Menu_OptionBlue", Input = "XboxTypeS_X" )
+mExtraActionsArray=( Action = "Menu_OptionYellow", Input = "XboxTypeS_Y" )
+mExtraActionsArray=( Action = "Menu_StartGame", Input = "XboxTypeS_Start" )
+mExtraActionsArray=( Action = "Menu_OptionBlue", Input = "KB_SettingsBlue" )
+mExtraActionsArray=( Action = "Menu_OptionYellow", Input = "KB_SettingsYellow" )
+mExtraActionsArray=( Action = "Menu_Confirm", Input = "KB_Accept" )
+mExtraActionsArray=( Action = "Menu_Cancel", Input = "KB_Cancel" )
+mExtraActionsArray=( Action = "Menu_StartGame", Input = "KB_Start" )
+mExtraActionsArray=( Action = "Party_InviteToGame", Input = "XboxTypeS_RightShoulder" )

+mInputMapArray=( Input="MouseScrollDown", PLATFORM=IPT_PC, GlyphToUse="ê" )
+mInputMapArray=( Input="MouseScrollUp", PLATFORM=IPT_PC, GlyphToUse="ê" )
+mInputMapArray=( Input="Enter", PLATFORM=IPT_PC, GlyphToUse="r" )
+mInputMapArray=( Input="LeftControl", PLATFORM=IPT_PC, GlyphToUse="c" )
+mInputMapArray=( Input="SpaceBar", PLATFORM=IPT_PC, GlyphToUse="p" )
+mInputMapArray=( Input="LeftShift", PLATFORM=IPT_PC, GlyphToUse="s" )
+mInputMapArray=( Input="KB_Accept", PLATFORM=IPT_PC, GlyphToUse="r" )
+mInputMapArray=( Input="KB_Cancel", PLATFORM=IPT_PC, GlyphToUse="e" )
+mInputMapArray=( Input="KB_Start", PLATFORM=IPT_PC, GlyphToUse="C" )
+mInputMapArray=( Input="KB_SettingsBlue", PLATFORM=IPT_PC, GlyphToUse="X" )
+mInputMapArray=( Input="RightMouseButton", PLATFORM=IPT_PC, GlyphToUse="ø" )
+mInputMapArray=( Input="LeftMouseButton", PLATFORM=IPT_PC, GlyphToUse="ð" )
+mInputMapArray=( Input="XboxTypeS_Start", PLATFORM=IPT_PC, GlyphToUse=">" )
+mInputMapArray=( Input="XboxTypeS_RightTrigger", PLATFORM=IPT_PC, GlyphToUse="x" )
+mInputMapArray=( Input="XboxTypeS_LeftTrigger", PLATFORM=IPT_PC, GlyphToUse="w" )
+mInputMapArray=( Input="XboxTypeS_Back", PLATFORM=IPT_PC, GlyphToUse=":" )
+mInputMapArray=( Input="XboxTypeS_RightShoulder", PLATFORM=IPT_PC, GlyphToUse="z" )
+mInputMapArray=( Input="XboxTypeS_LeftShoulder", PLATFORM=IPT_PC, GlyphToUse="y" )
+mInputMapArray=( Input="XboxTypeS_RightThumbstick", PLATFORM=IPT_PC, GlyphToUse="h" )
+mInputMapArray=( Input="XboxTypeS_LeftThumbstick", PLATFORM=IPT_PC, GlyphToUse="M" )
+mInputMapArray=( Input="XboxTypeS_Y", PLATFORM=IPT_PC, GlyphToUse="Y" )
+mInputMapArray=( Input="XboxTypeS_A", PLATFORM=IPT_PC, GlyphToUse="A" )
+mInputMapArray=( Input="XboxTypeS_B", PLATFORM=IPT_PC, GlyphToUse="B" )
+mInputMapArray=( Input="XboxTypeS_X", PLATFORM=IPT_PC, GlyphToUse="X" )
+mInputMapArray=( Input="XboxTypeS_DPad_Left", PLATFORM=IPT_PC, GlyphToUse="9" )
+mInputMapArray=( Input="XboxTypeS_DPad_Right", PLATFORM=IPT_PC, GlyphToUse="o" )
+mInputMapArray=( Input="LeftAlt", PLATFORM=IPT_PC, GlyphToUse="É" )

+mInputMapArray=( Input="XboxTypeS_A", PLATFORM=IPT_360, GlyphToUse="A" )
+mInputMapArray=( Input="XboxTypeS_B", PLATFORM=IPT_360, GlyphToUse="B" )
+mInputMapArray=( Input="XboxTypeS_X", PLATFORM=IPT_360, GlyphToUse="X" )
+mInputMapArray=( Input="XboxTypeS_Y", PLATFORM=IPT_360, GlyphToUse="Y" )
+mInputMapArray=( Input="XboxTypeS_Start", PLATFORM=IPT_360, GlyphToUse=">" )
+mInputMapArray=( Input="XboxTypeS_Back", PLATFORM=IPT_360, GlyphToUse=":" )
+mInputMapArray=( Input="XboxTypeS_RightTrigger", PLATFORM=IPT_360, GlyphToUse="x" )
+mInputMapArray=( Input="XboxTypeS_LeftTrigger", PLATFORM=IPT_360, GlyphToUse="w" )
+mInputMapArray=( Input="XboxTypeS_RightShoulder", PLATFORM=IPT_360, GlyphToUse="z" )
+mInputMapArray=( Input="XboxTypeS_LeftShoulder", PLATFORM=IPT_360, GlyphToUse="y" )
+mInputMapArray=( Input="XboxTypeS_RightThumbstick", PLATFORM=IPT_360, GlyphToUse="h" )
+mInputMapArray=( Input="XboxTypeS_LeftThumbstick", PLATFORM=IPT_360, GlyphToUse="M" )
+mInputMapArray=( Input="XboxTypeS_DPad_Left", PLATFORM=IPT_360, GlyphToUse="9" )
+mInputMapArray=( Input="XboxTypeS_DPad_Right", PLATFORM=IPT_360, GlyphToUse="o" )

+mInputMapArray=( Input="XboxTypeS_A", PLATFORM=IPT_PS3, GlyphToUse="A" )
+mInputMapArray=( Input="XboxTypeS_B", PLATFORM=IPT_PS3, GlyphToUse="B" )
+mInputMapArray=( Input="XboxTypeS_X", PLATFORM=IPT_PS3, GlyphToUse="X" )
+mInputMapArray=( Input="XboxTypeS_Y", PLATFORM=IPT_PS3, GlyphToUse="Y" )
+mInputMapArray=( Input="XboxTypeS_Start", PLATFORM=IPT_PS3, GlyphToUse=">" )
+mInputMapArray=( Input="XboxTypeS_Back", PLATFORM=IPT_PS3, GlyphToUse=":" )
+mInputMapArray=( Input="XboxTypeS_RightTrigger", PLATFORM=IPT_PS3, GlyphToUse="x" )
+mInputMapArray=( Input="XboxTypeS_LeftTrigger", PLATFORM=IPT_PS3, GlyphToUse="w" )
+mInputMapArray=( Input="XboxTypeS_RightShoulder", PLATFORM=IPT_PS3, GlyphToUse="z" )
+mInputMapArray=( Input="XboxTypeS_LeftShoulder", PLATFORM=IPT_PS3, GlyphToUse="y" )
+mInputMapArray=( Input="XboxTypeS_RightThumbstick", PLATFORM=IPT_PS3, GlyphToUse="h" )
+mInputMapArray=( Input="XboxTypeS_LeftThumbstick", PLATFORM=IPT_PS3, GlyphToUse="M" )
+mInputMapArray=( Input="XboxTypeS_DPad_Left", PLATFORM=IPT_PS3, GlyphToUse="9" )
+mInputMapArray=( Input="XboxTypeS_DPad_Right", PLATFORM=IPT_PS3, GlyphToUse="o" )

mEligableGlyphs[0]="q"
mEligableGlyphs[1]="w"
mEligableGlyphs[2]="e"
mEligableGlyphs[3]="r"
mEligableGlyphs[4]="t"
mEligableGlyphs[5]="y"
mEligableGlyphs[6]="u"
mEligableGlyphs[7]="i"
mEligableGlyphs[8]="o"
mEligableGlyphs[9]="p"
mEligableGlyphs[10]="a"
mEligableGlyphs[11]="s"
mEligableGlyphs[12]="d"
mEligableGlyphs[13]="f"
mEligableGlyphs[14]="g"
mEligableGlyphs[15]="h"
mEligableGlyphs[16]="j"
mEligableGlyphs[17]="k"
mEligableGlyphs[18]="l"
mEligableGlyphs[19]="z"
mEligableGlyphs[20]="x"
mEligableGlyphs[21]="c"
mEligableGlyphs[22]="v"
mEligableGlyphs[23]="b"
mEligableGlyphs[24]="n"
mEligableGlyphs[25]="m"
mEligableGlyphs[26]="Q"
mEligableGlyphs[27]="W"
mEligableGlyphs[28]="E"
mEligableGlyphs[29]="R"
mEligableGlyphs[30]="T"
mEligableGlyphs[31]="Y"
mEligableGlyphs[32]="U"
mEligableGlyphs[33]="I"
mEligableGlyphs[34]="O"
mEligableGlyphs[35]="P"
mEligableGlyphs[36]="A"
mEligableGlyphs[37]="S"
mEligableGlyphs[38]="D"
mEligableGlyphs[39]="F"
mEligableGlyphs[40]="G"
mEligableGlyphs[41]="H"
mEligableGlyphs[42]="J"
mEligableGlyphs[43]="K"
mEligableGlyphs[44]="L"
mEligableGlyphs[45]="Z"
mEligableGlyphs[46]="X"
mEligableGlyphs[47]="C"
mEligableGlyphs[48]="V"
mEligableGlyphs[49]="B"
mEligableGlyphs[50]="N"
mEligableGlyphs[51]="M"
mEligableGlyphs[52]="1"
mEligableGlyphs[53]="2"
mEligableGlyphs[54]="3"
mEligableGlyphs[55]="4"
mEligableGlyphs[56]="5"
mEligableGlyphs[57]="6"
mEligableGlyphs[58]="7"
mEligableGlyphs[59]="8"
mEligableGlyphs[60]="9"
mEligableGlyphs[61]="0"
mEligableGlyphs[62]="É"




;+mInputMapArray=( Action="ACTION_SHOOT", GlyphToUse="GBA_SHOOT" )

;+mInputMapArray=( InputButton="RB", PLATFORM=IPT_360, GlyphToUse="" )
;GBA_SHOOT -> RB

;GBA_SHOOT -> LB

;RB -> GLYPH_RB




